# Generated by Django 2.2.2 on 2019-06-25 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacionamiento',
            name='img',
            field=models.CharField(default='https://i.imgur.com/06j4AsO.png', max_length=999),
        ),
    ]
