# Generated by Django 2.2.2 on 2019-06-25 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_estacionamiento_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='Estacionamiento',
            new_name='estacionamiento',
        ),
    ]
