# Generated by Django 2.2.2 on 2019-06-25 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20190624_2143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuenta',
            old_name='contrastos',
            new_name='contratos',
        ),
    ]
