# Generated by Django 2.2.2 on 2019-06-25 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Vehiculo'),
        ),
    ]
