# Generated by Django 2.2.2 on 2019-06-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20190625_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='img',
            field=models.CharField(default='https://i.imgur.com/tcsXxV3.png', max_length=999),
        ),
        migrations.DeleteModel(
            name='Cuenta',
        ),
    ]
