# Generated by Django 2.2.2 on 2019-06-25 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0008_auto_20190625_0118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('direccion', models.CharField(max_length=200)),
                ('img', models.CharField(default='https://i.imgur.com/a7TW4aZ.png', max_length=999)),
                ('contratos', models.ManyToManyField(blank=True, to='web.Contrato')),
                ('estacionamientos', models.ManyToManyField(blank=True, to='web.Estacionamiento')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Vehiculo')),
            ],
        ),
    ]
