# Generated by Django 2.2.2 on 2019-06-25 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='direccion',
            field=models.CharField(default='DEFAULT', max_length=200),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='numero',
            field=models.IntegerField(default=0),
        ),
    ]
