# Generated by Django 2.2.2 on 2019-06-25 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20190625_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='modelo',
        ),
    ]
